### ISSUE TITLE
Write-Log not adding attributes to log file name

### ISSUE THREAD

**Issue by CodyDeVecht** [adbertram/PSADSync#14]
I noticed recently that the WriteLog function doesn't seem to be adding the attributes to the log file name which results in the file being appended indefinitely. It's possible we're doing something incorrectly but this seems to have occurred when we upgraded from version .64 to .88.

I run the script using another front end script for some pre-processing with a fairly simple configuration:
Invoke-AdSync @Parameters -Confirm:$False

**Comment by adbertram** [comment]
You could include the -Overwrite parameter to your WriteLog function invocations.

**Comment by CodyDeVecht** [comment]
Yes that is an option we have discussed, but then we have no historical logs beyond the most recent run.

**Comment by CodyDeVecht** [comment]
Yes that is an option we have discussed, but then we have no historical logs beyond the most recent run.

**Comment by adbertram** [comment]
Could you clarify 'doesn't seem to be adding the attributes to the log file'? That tells me it's not writing to the log file at all. Without overwriting, it will append indefinitely.

**Comment by CodyDeVecht** [comment]
Sorry for the confusion, I am specifically referring to the file name in this scenario. Previously, the log file name had the date and time it was created in the filename itself. More recently it seems that the filename is just PSADSync.csv. I could be misinterpreting the WriteLog function, or maybe this is something we modified during implementation that I was not aware of and when the module got updated it was overwritten.

Unfortunately GitHub is having issues with me uploading the screenshot I was hoping to share, so this example of a previous filename we had will have to suffice for now:
PSAdSync_log_12-10-21_11AM.csv

**Comment by CodyDeVecht** [comment]
Sorry for the confusion, I am specifically referring to the file name in this scenario. Previously, the log file name had the date and time it was created in the filename itself. More recently it seems that the filename is just PSADSync.csv. I could be misinterpreting the WriteLog function, or maybe this is something we modified during implementation that I was not aware of and when the module got updated it was overwritten.

Unfortunately GitHub is having issues with me uploading the screenshot I was hoping to share, so this example of a previous filename we had will have to suffice for now:
PSAdSync_log_12-10-21_11AM.csv

**Comment by adbertram** [comment]
I added it back. It should now create a log file for each run.

**Comment by CodyDeVecht** [comment]
Great! Thanks a ton @adbertram

**Comment by CodyDeVecht** [comment]
Great! Thanks a ton @adbertram
